### ISSUE TITLE
I do not know how to chat

### ISSUE THREAD

**Issue by cydoflax** [patedgeer/patedgeer.github.io#1]
so where are your projects before？？？

**Comment by patedgeer** [comment]
hahahahahhaahhaaha

cydoflax ***@***.***> 于2022年11月5日周六 20:07写道：

**Comment by cydoflax** [comment]
I do not want to use English anymore......

**Comment by cydoflax** [comment]
![屏幕截图 2022-11-12 074833](https://user-images.githubusercontent.com/112790268/201445391-5f8b9680-8a89-4846-9720-7cc4abc7e156.png)
Ahhhhhhhhhhh

**Comment by cydoflax** [comment]
Theater Missle Defense

**Comment by cydoflax** [comment]
hw.mail.163.com and mail.163.com look same

**Comment by cydoflax** [comment]
Oh,you use arcana?

**Comment by patedgeer** [comment]
obfs4 [2a02:180:6:1::4ffc]:4444 0E6683151788FF3D971B9D4FCD11C5984B1D05FE cert=HqzDz8I7XoMKnrF7YF25msh3g4r+pdoNFl8ogGHiolBEW7k+S0+NzUdUWYeOgX1C88FZZQ iat-mode=0
obfs4 88.99.6.209:51804 FDF90B9AC2466DD54B6A3F9DB09774CD47BFA9A7 cert=dDXmykTtwadQd7dMXIp/+eIqCIeJ/C7q/YW57oZO/Xbu2kOEYzOJkcnuhiMsRpi9ph3faw iat-mode=0
obfs4 142.47.107.150:8443 2B929392284EE96FB4B31A790059E2397182F156 cert=7LZa1KLdXsxb9SnmOJ9PDyYTb9fnIttUHOl9DjUu5EOf7nyPuhKtW+0syMrhJJ/UQLdNNg iat-mode=0
obfs4 64.251.148.240:35602 99D8CCA826C7F194752C6D5364A5A453C19A4AA9 cert=u/FfodJzDQ7xH5dUy0pubw4ATSyyGEssHDysQAJR39bsQnenDfjO3zbZ6lDdFHM0jqy/Rw iat-mode=0

**Comment by patedgeer** [comment]
vmess://eyJ2IjogIjIiLCAicHMiOiAiXHU2NmY0XHU2NWIwXHU0ZThlOjExLTEyIDEyOjAwIC1ieSBCdUxpbmsueHl6LSBcdTRlZTVcdTRlMGJcdTgyODJcdTcwYjlcdTRlMGRcdThiYTFcdTZkNDFcdTkxY2YiLCAiYWRkIjogIlx1NGY3Zlx1NzUyOFx1NTI0ZFx1OGJiMFx1NWY5N1x1NjZmNFx1NjViMFx1OGJhMlx1OTYwNSIsICJwb3J0IjogIjAiLCAiaWQiOiAiNmEzYmNjMDgtOWM3Ny00YzAyLTg0NGItNGE2OTRjNGYyZmVhIiwgImFpZCI6ICIwIiwgIm5ldCI6ICJ0Y3AiLCAidHlwZSI6ICJub25lIiwgImhvc3QiOiAiIiwgInBhdGgiOiAiIiwgInRscyI6ICIifQ==
vmess://eyJhZGQiOiAicG93ZXJzZXJ2aWNlLmNvbSIsICJhaWQiOiAwLCAiaG9zdCI6ICJ1azIudjJyYXlzZXJ2LmNvbSIsICJpZCI6ICIwNzY0YTU5OC04MmM0LTRiNDEtYmExMC01NTFhNjI1YmVlZDUiLCAibmV0IjogIndzIiwgInBhdGgiOiAiL3NzaG9jZWFuIiwgInBvcnQiOiA0NDMsICJwcyI6ICJnaXRodWIuY29tL1Bhd2Ryb2lkIC0gXHU3ZjhlXHU1NmZkQ2xvdWRGbGFyZVx1ODI4Mlx1NzBiOSAxMyIsICJ0bHMiOiAidGxzIiwgInR5cGUiOiAiYXV0byIsICJzZWN1cml0eSI6ICJhdXRvIiwgInNraXAtY2VydC12ZXJpZnkiOiB0cnVlLCAic25pIjogIiJ9

**Comment by cydoflax** [comment]
找不到Core，下载地址: https://github.com/v2fly/v2ray-core/releases

**Comment by cydoflax** [comment]
again

**Comment by cydoflax** [comment]
。。。
